### ISSUE TITLE
Implementar CalculaPrecoCarrinho

### ISSUE THREAD

**Issue by b2198** [mluisas/CarrinhoCompras#5]

**Comment by JoseAntonioPaiva** [comment]
``import java.math.BigDecimal;

public class CalculaPrecoCarrinho implements CalculaPreco<Carrinho>{

    @Override
    public BigDecimal calcular(Carrinho carrinho) {
        BigDecimal soma= BigDecimal.ZERO;
        carrinho.getProdutos().forEach((produto, quantidade) -> {
            soma.add(produto.getPreco().multiply(BigDecimal.valueOf(quantidade)));
        });
        return soma;
    }
}
